### ISSUE TITLE
Can't reproduce results from paper

### ISSUE THREAD

**Issue by Jbwasse2** [meera1hahn/NRNS#2]
Hello, after a fresh clone and following the instructions I am getting the following results when I run
```
python -W ignore run.py --dataset 'gibson' --path_type 'straight' --difficulty 'easy'
```

100%|███████████████████████████████████████████████████| 1000/1000 [1:22:39<00:00,  4.96s/it]

Type of Run:
Dataset: GIBSON
Data: STRAIGHT
Data Type: easy
Pose Noise: False; Actuation Noise: False

Stats of Runs:
Success Rate: 0.6630
SPL: 0.6087
Avg dist to goal: 1.0640
Avg taken path len - total: 3.9273
Avg taken path len - success: 2.3749
Avg gt path len - total: 2.2472
Avg gt path len - success: 2.1967

For excel in above order:
0.6630
0.6087
1.0640
3.9273
2.3749
2.2472
2.1967

which doesn't match with the 68% from your paper. Any thoughts on why this might be happening?

**Comment by Jbwasse2** [comment]
Just to add, I got the following
Easy, Straight - 68.00 (Paper) Vs 66.3 (Me)
Medium, Straight - 49.10 (Paper) Vs 45.3 (Me)
Hard, Straight - 23.82 (Paper) Vs 16.0 (Me)
Easy, Curve - 35.50 (Paper) Vs 15.7 (Me)
Medium, Curve - 23.90 (Paper) Vs 8.0 (Me)
Hard, Curve - 12.50 (Paper) Vs 3.0 (Me)

Off of the top of my head, I'd guess maybe our Habitat versions are different. I am using 0.2.1, what are you using?

**Comment by ffmpbgrnn** [comment]
Hi @Jbwasse2 , do you manage to match the results? Is it because of a different Habitat version?

**Comment by Jbwasse2** [comment]
I was not able to. Different versions of Habitat give different results (between versions 0.2.1 and 0.1.6), but as I recall this was like a 1% difference.

**Comment by recordmp3** [comment]
@Jbwasse2 I got exactly the same result as yours. May I know what other habitat version did you tried? (mine is 0.2.1)

**Comment by Jbwasse2** [comment]
I mentioned in my previous message that I tried version 0.1.6 and it only improved results by like 1%. Feel free to stop by CSL 164 if you'd like to chat :).

**Comment by recordmp3** [comment]
@Jbwasse2 Thank you :)! Maybe we can discuss a little after I read through all codes.

**Comment by recordmp3** [comment]
@Jbwasse2 May I know what version of scikit-fmm you used? Is that 2019.1.30? I find errors when installing scikit-fmm=2019.1.30. So, I installed scikit-fmm=2022.3.26 instead. I wonder whether this is the reason.

**Comment by Jbwasse2** [comment]
Ya I vaguely recall that there was a problem with scikit-fmm. I am still using 2019.1.30, but I think I had to change the code to get it to work with that version. If you can point me to the line that is throwing the error, I can let you know what I changed.

**Comment by recordmp3** [comment]
No, you do not need to change the version. 2019.1.30 was what they used.

**Comment by meera1hahn** [comment]
There were some bugs that were created during refactoring. Sorry about this. I have tried to find the main differences that were causing the issues especially for the curved episodes. If you run this now the numbers you should get for gibson are the following:

Easy, Straight - 0.701
Medium, Straight - 0.507
Hard, Straight - 0.2122
Easy, Curve - 0.314
Medium, Curve - 0.2200
Hard, Curve - 0.119

**Comment by recordmp3** [comment]
@meera1hahn Thank you for your reply! A small typo: the success rate of Medium Curve is not 0.314?

**Comment by meera1hahn** [comment]
@recordmp3  fixed sorry about that

**Comment by bareblackfoot** [comment]
I think the main problem of the performance drop is the distance estimation part.
It takes 0.5 as a default value for the unexplored node feature.
After changing it to the nearest explored node feature I got higher results.
Check it out in my forked repository!
