### ISSUE TITLE
2d RGB/Semantic maps

### ISSUE THREAD

**Issue by bareblackfoot** [meera1hahn/NRNS#3]
Thank you for sharing your great work!
I want to know how you made your 2d maps of RGB / semantics
Would you provide the code for that?

**Comment by meera1hahn** [comment]
Hi,

You can download the top down maps from here: https://drive.google.com/file/d/14ZVplcKR_IrzXBfYLs_9Lf8DHPkJ7Dzv/view?usp=sharing

For code on how to use them please refer to the following files:

1. `https://github.com/meera1hahn/NRNS/blob/e0745fbd301984a6512b11a69421cbe7831c6c97/src/image_nav/visualize.py`
2. `https://github.com/meera1hahn/NRNS/blob/e0745fbd301984a6512b11a69421cbe7831c6c97/src/utils/vis_utils.py`

Note in this code the the NRNS topological graph is drawn over the top down map and creates a video containing the frames of the agents current view, goal image and top down map.

**Comment by bareblackfoot** [comment]
Thank you for your reply :)
But I wanted to know the code for making the map.. haha. Maybe you cannot share it.
Anyway, thanks.

**Comment by meera1hahn** [comment]
You need to use the Habitat Simulator's orthographic projection cameras over the scene to generate whichever projection you are interested in.

https://github.com/facebookresearch/habitat-lab/issues/812

**Comment by bareblackfoot** [comment]
You mean that you defined a camera for the RGB colorized top-down map!
It helped me a lot. Thank you so much.. :)
